### ISSUE TITLE
Hard coding the facial keypoints

### ISSUE THREAD

**Issue by dvigneshwer** [mrgloom/Kaggle-Facial-Keypoints-Detection-Solutions#1]
The mean model is basically the mean of the different coordinates keypoint values.
These values remain same for all test cases, no change in keypoint occurs.

In danielnouri blog, he creates a deepnet model for predicting the keypoint for a given test image.

**Comment by mrgloom** [comment]
Yes, mean model is like in `A simple benchmark` section from https://www.kaggle.com/c/facial-keypoints-detection/details/getting-started-with-r , but here it is written in python.
